### ISSUE TITLE
arm64 support

### ISSUE THREAD

**Issue by dkrizic** [groundcover-com/caretta#35]
Hi,

I read your article in https://medium.com/better-programming/improve-cluster-monitoring-with-network-mapping-in-grafana-fa8bb479fd47

Thank you for that. I tried Caretta on my hybrid home cluster that has hybrid architecture amd64 and arm64 and I see that you don't provide multi architecture images that run on both architectures.

So please add arm64 support.

**Comment by udiz** [comment]
Hey @dkrizic, PR #50 addresses this issue and adds support for arm64 :) Make sure to run `helm repo update groundcover` to run the latest version.
